on: [workflow_dispatch]
name: Deploy Services to AKS

env:
  DOTNET_VERSION: "10.0.x"
  NODE_VERSION: "22.x"

jobs:

  deploy-container-app:
    name: Deploy Angular App
    runs-on: ubuntu-latest
    if: github.repository_owner == 'BpsLogicBuilder'
    permissions:
      id-token: write
      contents: read
    steps:

    - name: Checkout repository
      uses: actions/checkout@v6

    - uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5
      with:
        client-id: ${{ secrets.ARM_DEPLOYER_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Get Deployment Outputs
      id: get_deployment_outputs
      env:
        RESOURCE_GROUP: ${{ secrets.AZURE_RG_ENROLLMENT_AKS }}
      run: |
        ACR_NAME=$(az deployment group show --resource-group ${{ env.RESOURCE_GROUP }} --name main --query properties.outputs.acrName.value -o tsv)
        echo "::add-mask::$ACR_NAME"

        APP_CONFIG_ENDPOINT=$(az deployment group show --resource-group ${{ env.RESOURCE_GROUP }} --name main --query properties.outputs.appConfigurationEndPoint.value -o tsv)
        echo "::add-mask::$APP_CONFIG_ENDPOINT"

        AKS_CLUSTER_NAME=$(az deployment group show --resource-group ${{ env.RESOURCE_GROUP }} --name main --query properties.outputs.aksClusterName.value -o tsv)
        echo "::add-mask::$AKS_CLUSTER_NAME"

        ENROLLMENT_APP_NAMESPACE=$(az deployment group show --resource-group ${{ env.RESOURCE_GROUP }} --name main --query properties.outputs.kubernetesNamespace.value -o tsv)
        echo "::add-mask::$ENROLLMENT_APP_NAMESPACE"

        ENROLLMENT_ANGULAR_SERVICEACCOUNT_NAME=$(az deployment group show --resource-group ${{ env.RESOURCE_GROUP }} --name main --query properties.outputs.enrollmentAngularServiceAccountName.value -o tsv)
        echo "::add-mask::$ENROLLMENT_ANGULAR_SERVICEACCOUNT_NAME"

        echo "acr_name=$ACR_NAME" >> $GITHUB_OUTPUT
        echo "app_config_endpoint=$APP_CONFIG_ENDPOINT" >> $GITHUB_OUTPUT
        echo "aks_cluster_name=$AKS_CLUSTER_NAME" >> $GITHUB_OUTPUT
        echo "enrollment_app_namespace=$ENROLLMENT_APP_NAMESPACE" >> $GITHUB_OUTPUT
        echo "enrollment_angular_serviceaccount_name=$ENROLLMENT_ANGULAR_SERVICEACCOUNT_NAME" >> $GITHUB_OUTPUT
        
    - name: Log in to Azure Container Registry
      env:
        RESOURCE_GROUP: ${{ secrets.AZURE_RG_ENROLLMENT_AKS }}
        ACR_NAME: ${{ steps.get_deployment_outputs.outputs.acr_name }}
      run: |
          az acr login --name ${{ env.ACR_NAME }}

    - name: Build and Upload Image
      env:
        IMAGE_TAG: "v1.0.${{ github.run_number }}"
        IMAGE_NAME: "enrollmentangular"
        ACR_LOGIN_SERVER_NAME: ${{ steps.get_deployment_outputs.outputs.acr_name }}.azurecr.io
        TELERIK_LICENSE: ${{ secrets.TELERIK_LICENSE }}
      run: |
        echo "ACR LOGIN SERVER NAME ${{ env.ACR_LOGIN_SERVER_NAME }}"
        docker buildx build --secret id=kendo_license,env=TELERIK_LICENSE -t "${{env.ACR_LOGIN_SERVER_NAME}}/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}" -t "${{env.ACR_LOGIN_SERVER_NAME}}/${{env.IMAGE_NAME}}:latest" --push .

    - name: Get AKS Credentials
      env:
        RESOURCE_GROUP: ${{ secrets.AZURE_RG_ENROLLMENT_AKS }}
        AKS_CLUSTER_NAME: ${{ steps.get_deployment_outputs.outputs.aks_cluster_name }}
      run: |
        az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER_NAME }}

    - name: Get Load Balancer IP
      id: get_ip
      run: |
        LOAD_BALANCER_IP=$(kubectl get service nginx-ingress-ingress-nginx-controller -n ingress-nginx -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
        echo "::add-mask::$LOAD_BALANCER_IP"

        echo "load_balancer_ip=$LOAD_BALANCER_IP" >> $GITHUB_OUTPUT

    - name: Deploy Manifext
      env:
        ACR_NAME: ${{ steps.get_deployment_outputs.outputs.acr_name }}
        APP_CONFIG_ENDPOINT: ${{ steps.get_deployment_outputs.outputs.app_config_endpoint }}
        IMAGE_TAG: "v1.0.${{ github.run_number }}"
        ENROLLMENT_APP_NAMESPACE: ${{ steps.get_deployment_outputs.outputs.enrollment_app_namespace }}
        ENROLLMENT_ANGULAR_SERVICEACCOUNT_NAME: ${{ steps.get_deployment_outputs.outputs.enrollment_angular_serviceaccount_name }}
        LOAD_BALANCER_IP: ${{ steps.get_ip.outputs.load_balancer_ip }}
      run: |
        sed -e "s|ACR_NAME|${{ env.ACR_NAME }}|g" \
        -e "s|APP_CONFIG_ENDPOINT|${{ env.APP_CONFIG_ENDPOINT }}|g" \
        -e "s|IMAGE_TAG|${{ env.IMAGE_TAG }}|g" \
        -e "s|LOAD_BALANCER_IP|${{ env.LOAD_BALANCER_IP }}|g" \
        -e "s|ENROLLMENT_ANGULAR_SERVICEACCOUNT_NAME|${{ env.ENROLLMENT_ANGULAR_SERVICEACCOUNT_NAME }}|g" \
        -e "s|ENROLLMENT_APP_NAMESPACE|${{ env.ENROLLMENT_APP_NAMESPACE }}|g" \
        infrastructure/aks/deployment.yaml | kubectl apply -f - -n ${{ env.ENROLLMENT_APP_NAMESPACE }}
